### ISSUE TITLE
Define 'get_fave' method in 'app.py'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/interview-meetup#90]
We will define the `get_fave` method within `app.py`.  This method will handle the ajax [request](https://github.com/jeff1evesque/interview-meetup/issues/84) from `ajax_preload_fave.js`, and return a list of _group ids_ that were marked as favorites.

**Comment by jeff1evesque** [comment]
We need to resolve the following trace error:

``` python
127.0.0.1 - - [17/Feb/2015 16:27:35] "POST /get_fave/ HTTP/1.1" 200 -
127.0.0.1 - - [17/Feb/2015 16:28:04] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Feb/2015 16:28:05] "GET /static/css/app.css HTTP/1.1" 304 -
127.0.0.1 - - [17/Feb/2015 16:28:05] "GET /static/css/font-awesome.css HTTP/1.1" 304 -
127.0.0.1 - - [17/Feb/2015 16:28:05] "GET /static/js/jquery-2.1.1.js HTTP/1.1" 304 -
127.0.0.1 - - [17/Feb/2015 16:28:05] "GET /static/js/app.js HTTP/1.1" 304 -
127.0.0.1 - - [17/Feb/2015 16:28:05] "GET /static/js/toggle_favicon.js HTTP/1.1" 304 -
127.0.0.1 - - [17/Feb/2015 16:28:05] "GET /static/js/ajax_data.js HTTP/1.1" 304 -
127.0.0.1 - - [17/Feb/2015 16:28:05] "GET /static/js/ajax_preload.js HTTP/1.1" 304 -
'NoneType' object is not iterable
127.0.0.1 - - [17/Feb/2015 16:28:06] "POST /get_fave/ HTTP/1.1" 200 -
127.0.0.1 - - [17/Feb/2015 16:28:08] "POST /my_fave/ HTTP/1.1" 200 -
```

Specifically, the error `'NoneType' object is not iterable` is caused by the following:

``` python
...
    # remove 'gid-' prefix, convert each element to 'int' type
    try:
      meetup_events_processed = [int(event.replace('gid-', '')) for event in meetup_events]
      flag_proceed = True
    except Exception, error:
      print error
...
```

**Comment by jeff1evesque** [comment]
We need to encode our `return` in `get_fave` method.  This will allow `ajax_preload.js` to [toggle](https://github.com/jeff1evesque/interview-meetup/issues/84#issuecomment-74838201) the necessary classes on specified DOM elements.

**Comment by jeff1evesque** [comment]
Our stack trace has improved:

``` python
 * Detected change in 'app.py', reloading
 * Restarting with reloader
127.0.0.1 - - [18/Feb/2015 04:47:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Feb/2015 04:47:24] "GET /static/css/app.css HTTP/1.1" 304 -
127.0.0.1 - - [18/Feb/2015 04:47:24] "GET /static/css/font-awesome.css HTTP/1.1" 304 -
127.0.0.1 - - [18/Feb/2015 04:47:24] "GET /static/js/jquery-2.1.1.js HTTP/1.1" 304 -
127.0.0.1 - - [18/Feb/2015 04:47:24] "GET /static/js/app.js HTTP/1.1" 304 -
127.0.0.1 - - [18/Feb/2015 04:47:24] "GET /static/js/toggle_favicon.js HTTP/1.1" 304 -
127.0.0.1 - - [18/Feb/2015 04:47:24] "GET /static/js/ajax_data.js HTTP/1.1" 304 -
127.0.0.1 - - [18/Feb/2015 04:47:24] "GET /static/js/ajax_preload.js HTTP/1.1" 200 -
127.0.0.1 - - [18/Feb/2015 04:47:25] "POST /get_fave/ HTTP/1.1" 200 -
```

**Comment by jeff1evesque** [comment]
We need to resolve an edge case to an `if` statement within the `get_fave` method.  Specifically, when no `intersection` is returned, nothing is returned within the _flask_ application.  This causes the following trace error:

``` python
...
127.0.0.1 - - [18/Feb/2015 13:07:32] "POST /get_fave/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
```
