### ISSUE TITLE
Create 'data_retriever.py'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/interview-meetup#91]
We will create `data_get_faves.py`.  This script will receive a list of _group ids_, as an argument [supplied](https://github.com/jeff1evesque/interview-meetup/issues/84) from `ajax_preload_fave.js`, and return the _group ids_ contained within `tbl_fave_gid`, with respect to the current `uid`.

**Comment by jeff1evesque** [comment]
We need to resolve the following trace error:

``` python
$ python app.py
Traceback (most recent call last):
  File "app.py", line 6, in <module>
    from package.database.data_retriever import Get_Fave
  File "/var/www/html/interview-meetup/package/database/data_retriever.py", line 37
    if self.connector.return_error(): self.list_error.append( self.connector.return_er$
                                                                                      ^
SyntaxError: invalid syntax
```

**Comment by jeff1evesque** [comment]
We need to resolve the following trace error:

``` python
...
  File "/var/www/html/interview-meetup/app.py", line 74, in get_fave
    return get_fave.fave_intersection( meetup_events_processed, fave_uid )
TypeError: fave_intersection() takes exactly 2 arguments (3 given)
```

**Comment by jeff1evesque** [comment]
We need to resolve the following trace error:

``` python
...
  File "/var/www/html/interview-meetup/app.py", line 73, in get_fave
    return get_fave.fave_intersection( meetup_events_processed, fave_uid )
  File "/var/www/html/interview-meetup/package/database/data_retriever.py", line 31, in fave_intersection
    response = self.connector.sql_command( sql_statement, 'select', args )
  File "/var/www/html/interview-meetup/package/database/db_query.py", line 45, in sql_command
    self.conn.rollback()
OperationalError: (2006, 'MySQL server has gone away')
```

**Comment by jeff1evesque** [comment]
After we remove the entire `db_my_faves` database, and `sudo reboot`, the above trace error was replaced with the following:

``` python
...
  File "/var/www/html/interview-meetup/package/database/data_retriever.py", line 31, in fave_intersection
    response = self.connector.sql_command( sql_statement, 'select', args )
  File "/var/www/html/interview-meetup/package/database/db_query.py", line 35, in sql_command
    self.cursor.execute( sql_statement, sql_args )
AttributeError: 'SQL' object has no attribute 'cursor'
```

However, when the database exists, the previous error is still displayed:

``` python
...
  File "/var/www/html/interview-meetup/app.py", line 73, in get_fave
    print get_fave.fave_intersection( meetup_events_processed, fave_uid )
  File "/var/www/html/interview-meetup/package/database/data_retriever.py", line 31, in fave_intersection
    response = self.connector.sql_command( sql_statement, 'select', args )
  File "/var/www/html/interview-meetup/package/database/db_query.py", line 45, in sql_command
    self.conn.rollback()
OperationalError: (2006, 'MySQL server has gone away')
```

**Comment by jeff1evesque** [comment]
The remaining trace error `AttributeError: 'SQL' object has no attribute 'cursor'` will be resolved by #112, and #113.

**Comment by jeff1evesque** [comment]
Implementing the following from `app.py`:

```
    # return intersection between database, and current values
    if flag_proceed:
      get_fave = Get_Fave()
      intersection = get_fave.fave_intersection( meetup_events_processed, fave_uid )
      if intersection: print intersection
```

prints out the following list structure:

```
[((12607092L,),), ((6737712L,),), ((6737712L,),), ((6737712L,),), ((6737712L,),)]
```

However, we need it to be a simpler structure:

```
[12607092L, 6737712L, 6737712L, 6737712L, 6737712L]
```

Therefore, we need to make some adjustments within the following lines from `data_retriever.py`:

``` python
...
      response = self.connector.sql_command( sql_statement, 'select', args )

      if len(response['result']) > 0:
        list_intersection.append( response['result'] )
...
```

**Comment by jeff1evesque** [comment]
After we have resolved #118, we will change the following:

``` python
...
      response = self.connector.sql_command( sql_statement, 'select', args )

      if len(response['result']) > 0:
        list_intersection.append( response['result'][0][0] )
...
```

to the following:

``` python
...
      response = self.connector.sql_command( sql_statement, 'select', args )

      if response['result']:
        list_intersection.append( response['result'][0][0] )
...
```

**Note:** we need to provide logic for the edge case where `response` does not return anything.  Specifically, we will need to resolve the following trace error:

``` python
...
127.0.0.1 - - [18/Feb/2015 13:07:32] "POST /get_fave/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
```

**Comment by jeff1evesque** [comment]
The above statement is an [edge case](https://github.com/jeff1evesque/interview-meetup/issues/90#issuecomment-74959967) within the `get_fave` method in `app.py`.  Specifically, the `if` statement does not have a corresponding `else` statement, when no _intersection_ is found.  So, the above issue is now obsolete within this thread.

**Comment by jeff1evesque** [comment]
We need to resolve the following trace error:

``` python
...
  File "/var/www/html/interview-meetup/app.py", line 73, in get_fave
  File "/var/www/html/interview-meetup/app.py", line 73, in get_fave
    intersection = get_fave.fave_intersection( meetup_events_processed, fave_uid )
  File "/var/www/html/interview-meetup/package/database/data_retriever.py", line 33, in fave_intersection
    if len(response['result']) > 0:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Specifically, the `NoneType` can be avoided by implementing the following within `fave_intersection`:

``` python
...
    for gid in list_events:
      # insert 'fave' into 'tbl_fave_gid'
      sql_statement = 'SELECT gid FROM tbl_fave_gid WHERE gid=%s AND uid_created=%s'
      args = (gid, uid)
      response = self.connector.sql_command( sql_statement, 'select', args )

      if response['result']:
        list_intersection.append( response['result'][0][0] )
...
```

**Comment by jeff1evesque** [comment]
b5a2117: we are still presented a similar trace error:

``` python
...
  File "/var/www/html/interview-meetup/app.py", line 73, in get_fave
    intersection = get_fave.fave_intersection( meetup_events_processed, fave_uid )
  File "/var/www/html/interview-meetup/package/database/data_retriever.py", line 33, in fave_intersection
    if response['result']:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by jeff1evesque** [comment]
We need to implement the following set of _nested_ `if` statements within the `fave_intersection` method:

``` python
...
    for gid in list_events:
      # insert 'fave' into 'tbl_fave_gid'
      sql_statement = 'SELECT gid FROM tbl_fave_gid WHERE gid=%s AND uid_created=%s'
      args = (gid, uid)
      response = self.connector.sql_command( sql_statement, 'select', args )

      if response:
        if response['result']:
          list_intersection.append( response['result'][0][0] )
...
```
